CREATE TABLE `thaali_data_tbl` (
  `THAALI_DATE` date NOT NULL,
  `THAALI_DAY` varchar(12) DEFAULT NULL,
  `MENU` varchar(45) NOT NULL,
  `COOKNAME` varchar(45) DEFAULT NULL,
  `INSTRUCTIONS` varchar(250) DEFAULT NULL,
  `ADMIN_NAME` varchar(45) NOT NULL,
  `CREATION_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `THAALI_STATUS` varchar(20) NOT NULL,
  `VISIBLE_TO_USERS` varchar(10) NOT NULL,
  PRIMARY KEY (`THAALI_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='This table will store the data for thaali for every day.';


CREATE TABLE `thaali_feedback` (
  `THAALI_DATE` date DEFAULT NULL,
  `EJAMAAT_ID` varchar(12) NOT NULL,
  `FIRST_NAME` varchar(45) NOT NULL,
  `FAMILY_NAME` varchar(45) NOT NULL,
  `FAMILY_GROUP_ID` int(11) NOT NULL,
  `THAALI_CATEGORY` varchar(12) NOT NULL,
  `THAALI_FEEDBACK` varchar(250) NOT NULL,
  `THAALI_FEEDBACK_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `THAALI_MENU` varchar(45) DEFAULT NULL,
  `THAALI_QUALITY` varchar(45) DEFAULT NULL,
  `THAALI_QUANTITY` varchar(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `thaali_menu_tbl` (
  `MENU` varchar(100) NOT NULL,
  `USERNAME` varchar(45) NOT NULL,
  PRIMARY KEY (`MENU`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `thaali_region` (
  `REGION_NAME` varchar(45) NOT NULL,
  `REGION_DESC` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`REGION_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `user_profile_tbl` (
  `EJAMAAT_ID` varchar(12) NOT NULL,
  `PASSWORD` varchar(12) NOT NULL,
  `HOF_EJAMAAT_ID` varchar(12) NOT NULL,
  `FAMILY_NAME` varchar(45) NOT NULL,
  `FIRST_NAME` varchar(45) NOT NULL,
  `USER_ROLE` varchar(12) NOT NULL,
  `THAALI_CATEGORY` varchar(12) NOT NULL,
  `FAMILY_GROUP_ID` int(11) NOT NULL,
  `USER_LOCATION` varchar(45) NOT NULL,
  PRIMARY KEY (`EJAMAAT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='This table will hold the profile information of the user.';



CREATE TABLE `user_thaali_data_tbl` (
  `THAALI_DATE` date NOT NULL,
  `FAMILY_GROUP_ID` int(11) NOT NULL,
  `FIRST_NAME` varchar(45) NOT NULL,
  `FAMILY_NAME` varchar(45) NOT NULL,
  `THAALI_CATEGORY` varchar(20) NOT NULL,
  `USER_THAALI_STATUS` varchar(20) NOT NULL,
  `INSTRUCTIONS` varchar(250) DEFAULT NULL,
  `USER_LOCATION` varchar(45) NOT NULL,
  PRIMARY KEY (`THAALI_DATE`,`FAMILY_GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

